package multiparty

import (
	"io"

	"github.com/tuneinsight/lattigo/v6/ring"

	"github.com/tuneinsight/lattigo/v6/core/rlwe"
)

// KeySwitchProtocol is the structure storing the parameters and precomputations for the collective key-switching protocol.
type KeySwitchProtocol struct {
	params       rlwe.Parameters
	noise        ring.DistributionParameters
	noiseSampler ring.Sampler
}

// KeySwitchShare is a type for the KeySwitch protocol shares.
type KeySwitchShare struct {
	Value ring.Poly
}

// KeySwitchCRP is a type for common reference polynomials in the KeySwitch protocol.
type KeySwitchCRP struct {
	Value ring.Poly
}

// NewKeySwitchProtocol creates a new [KeySwitchProtocol] that will be used to perform a collective key-switching on a ciphertext encrypted under a collective public-key, whose
// secret-shares are distributed among j parties, re-encrypting the ciphertext under another public-key, whose secret-shares are also known to the
// parties.
func NewKeySwitchProtocol(params rlwe.ParameterProvider, noiseFlooding ring.DistributionParameters) (KeySwitchProtocol, error) {
	_ = "STUB: not implemented"
	return *new(KeySwitchProtocol), nil
}

// Sanity check, this error should not happen.

// EncFreshSK + sigmaSmudging

// Sanity check, this error should not happen.

// AllocateShare allocates the shares of the KeySwitchProtocol
func (cks KeySwitchProtocol) AllocateShare(level int) KeySwitchShare {
	_ = "STUB: not implemented"
	return *new(KeySwitchShare)
}

// SampleCRP samples a common random polynomial to be used in the KeySwitch protocol from the provided
// common reference string.
func (cks KeySwitchProtocol) SampleCRP(level int, crs CRS) KeySwitchCRP {
	_ = "STUB: not implemented"
	return *new(KeySwitchCRP)
}

// GenShare computes a party's share in the KeySwitchcol from secret-key skInput to secret-key skOutput.
// ct is the [rlwe.Ciphertext] to keyswitch. Note that ct.Value[0] is not used by the function and can be nil/zero.
//
// Expected noise: ctNoise + encFreshSk + smudging
func (cks KeySwitchProtocol) GenShare(skInput, skOutput *rlwe.SecretKey, ct *rlwe.Ciphertext, shareOut *KeySwitchShare) {
	_ = "STUB: not implemented"
	return
}

// c1NTT * (skIn - skOut)

// InvNTT(c1NTT * (skIn - skOut)) + e

// c1NTT * (skIn - skOut) + e

// AggregateShares is the second part of the unique round of the [KeySwitchProtocol] protocol. Upon receiving the j-1 elements each party computes:
//
// [ctx[0] + sum((skInput_i - skOutput_i) * ctx[0] + e_i), ctx[1]]
func (cks KeySwitchProtocol) AggregateShares(share1, share2 KeySwitchShare, shareOut *KeySwitchShare) (err error) {
	_ = "STUB: not implemented"
	return nil
}

// KeySwitch performs the actual keyswitching operation on a ciphertext ct and put the result in opOut
func (cks KeySwitchProtocol) KeySwitch(ctIn *rlwe.Ciphertext, combined KeySwitchShare, opOut *rlwe.Ciphertext) {
	_ = "STUB: not implemented"
	return
}

// Level returns the level of the target share.
func (ckss KeySwitchShare) Level() int { _ = "STUB: not implemented"; return 0 }

// BinarySize returns the serialized size of the object in bytes.
func (ckss KeySwitchShare) BinarySize() int { _ = "STUB: not implemented"; return 0 }

// WriteTo writes the object on an [io.Writer]. It implements the [io.WriterTo]
// interface, and will write exactly object.BinarySize() bytes on w.
//
// Unless w implements the [buffer.Writer] interface (see lattigo/utils/buffer/writer.go),
// it will be wrapped into a [bufio.Writer]. Since this requires allocations, it
// is preferable to pass a [buffer.Writer] directly:
//
//   - When writing multiple times to a [io.Writer], it is preferable to first wrap the
//     [io.Writer] in a pre-allocated [bufio.Writer].
//   - When writing to a pre-allocated var b []byte, it is preferable to pass
//     buffer.NewBuffer(b) as w (see lattigo/utils/buffer/buffer.go).
func (ckss KeySwitchShare) WriteTo(w io.Writer) (n int64, err error) {
	_ = "STUB: not implemented"
	return 0, nil

	// ReadFrom reads on the object from an [io.Writer]. It implements the
	// [io.ReaderFrom] interface.
	//
	// Unless r implements the [buffer.Reader] interface (see see lattigo/utils/buffer/reader.go),
	// it will be wrapped into a [bufio.Reader]. Since this requires allocation, it
	// is preferable to pass a [buffer.Reader] directly:
	//
	//   - When reading multiple values from a [io.Reader], it is preferable to first
	//     first wrap [io.Reader] in a pre-allocated [bufio.Reader].
	//   - When reading from a var b []byte, it is preferable to pass a buffer.NewBuffer(b)
	//     as w (see lattigo/utils/buffer/buffer.go).
}

func (ckss *KeySwitchShare) ReadFrom(r io.Reader) (n int64, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// MarshalBinary encodes a KeySwitch share on a slice of bytes.
func (ckss KeySwitchShare) MarshalBinary() (p []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary decodes a slice of bytes generated by
// [KeySwitchShare.MarshalBinary] or[KeySwitchShare.WriteTo] on the object.
func (ckss *KeySwitchShare) UnmarshalBinary(p []byte) (err error) {
	_ = "STUB: not implemented"
	return nil
}
