package rlwe

import (
	"io"

	"github.com/tuneinsight/lattigo/v6/ring"
	"github.com/tuneinsight/lattigo/v6/ring/ringqp"
	"github.com/tuneinsight/lattigo/v6/utils/structs"
)

// GadgetCiphertext is a struct for storing an encrypted
// plaintext times the gadget power matrix.
type GadgetCiphertext struct {
	BaseTwoDecomposition int
	Value                structs.Matrix[VectorQP]
}

// NewGadgetCiphertext returns a new [GadgetCiphertext] key with pre-allocated zero-value.
// [GadgetCiphertext] is always in the NTT domain.
// A [GadgetCiphertext] is created by default at degree 1 with the the maximum levelQ and levelP and with no base 2 decomposition.
// Give the optional GadgetCiphertextParameters struct to create a GadgetCiphertext with at a specific degree, levelQ, levelP and/or base 2 decomposition.
func NewGadgetCiphertext(params ParameterProvider, Degree, LevelQ, LevelP, BaseTwoDecomposition int) *GadgetCiphertext {
	_ = "STUB: not implemented"
	return nil
}

// Degree returns the degree of the target ciphertext.
func (ct GadgetCiphertext) Degree() int { _ = "STUB: not implemented"; return 0 }

// LevelQ returns the level of the modulus Q of the target ciphertext.
func (ct GadgetCiphertext) LevelQ() int { _ = "STUB: not implemented"; return 0 }

// LevelP returns the level of the modulus P of the target ciphertext.
func (ct GadgetCiphertext) LevelP() int { _ = "STUB: not implemented"; return 0 }

// BaseRNSDecompositionVectorSize returns the number of element in the RNS decomposition basis.
func (ct GadgetCiphertext) BaseRNSDecompositionVectorSize() int {
	_ = "STUB: not implemented"
	return 0

	// BaseTwoDecompositionVectorSize returns the number of element in the power of two decomposition basis for each prime of Q.
}

func (ct GadgetCiphertext) BaseTwoDecompositionVectorSize() (base []int) {
	_ = "STUB: not implemented"
	return nil
}

// Equal checks two ciphertexts for equality.
func (ct GadgetCiphertext) Equal(other *GadgetCiphertext) bool {
	_ = "STUB: not implemented"
	return false
}

// CopyNew creates a deep copy of the receiver ciphertext and returns it.
func (ct GadgetCiphertext) CopyNew() (ctCopy *GadgetCiphertext) {
	_ = "STUB: not implemented"
	return nil
}

// BinarySize returns the serialized size of the object in bytes.
func (ct GadgetCiphertext) BinarySize() (dataLen int) { _ = "STUB: not implemented"; return 0 }

// WriteTo writes the object on an [io.Writer]. It implements the [io.WriterTo]
// interface, and will write exactly object.BinarySize() bytes on w.
//
// Unless w implements the [buffer.Writer] interface (see lattigo/utils/buffer/writer.go),
// it will be wrapped into a [bufio.Writer]. Since this requires allocations, it
// is preferable to pass a [buffer.Writer] directly:
//
//   - When writing multiple times to a [io.Writer], it is preferable to first wrap the
//     io.Writer in a pre-allocated [bufio.Writer].
//   - When writing to a pre-allocated var b []byte, it is preferable to pass
//     buffer.NewBuffer(b) as w (see lattigo/utils/buffer/buffer.go).
func (ct GadgetCiphertext) WriteTo(w io.Writer) (n int64, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// ReadFrom reads on the object from an [io.Writer]. It implements the
// [io.ReaderFrom] interface.
//
// Unless r implements the [buffer.Reader] interface (see see lattigo/utils/buffer/reader.go),
// it will be wrapped into a [bufio.Reader]. Since this requires allocation, it
// is preferable to pass a [buffer.Reader] directly:
//
//   - When reading multiple values from a [io.Reader], it is preferable to first
//     first wrap [io.Reader] in a pre-allocated [bufio.Reader].
//   - When reading from a var b []byte, it is preferable to pass a buffer.NewBuffer(b)
//     as w (see lattigo/utils/buffer/buffer.go).
func (ct *GadgetCiphertext) ReadFrom(r io.Reader) (n int64, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// MarshalBinary encodes the object into a binary form on a newly allocated slice of bytes.
func (ct GadgetCiphertext) MarshalBinary() (data []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary decodes a slice of bytes generated by
// [GadgetCiphertext.MarshalBinary] or [GadgetCiphertext.WriteTo] on the object.
func (ct *GadgetCiphertext) UnmarshalBinary(p []byte) (err error) {
	_ = "STUB: not implemented"
	return nil
}

// AddPolyTimesGadgetVectorToGadgetCiphertext takes a plaintext polynomial and a list of [GadgetCiphertext] and adds the
// plaintext times the RNS and BIT decomposition to the i-th element of the i-th ciphertext. This method returns
// an error if len(cts) > 2.
func AddPolyTimesGadgetVectorToGadgetCiphertext(pt ring.Poly, cts []GadgetCiphertext, ringQP ringqp.Ring, buff ring.Poly) (err error) {
	_ = "STUB: not implemented"
	return nil
}

// P * pt

// 1 * pt

// e + (m * P * w^2j) * (q_star * q_tild) mod QP
//
// q_prod = prod(q[i*#Pi+j])
// q_star = Q/qprod
// q_tild = q_star^-1 mod q_prod
//
// Therefore : (pt * P * w^2j) * (q_star * q_tild) = pt*P*w^2j mod q[i*#Pi+j], else 0

// Handle cases where #pj does not divide #qi

// w^2j

// GadgetPlaintext stores a plaintext value times the gadget vector.
type GadgetPlaintext struct {
	Value structs.Vector[ring.Poly]
}

// NewGadgetPlaintext creates a new [GadgetPlaintext] from value, which can be either uint64, int64 or *[ring.Poly].
// Plaintext is returned in the NTT and Montgomery domain.
func NewGadgetPlaintext(params Parameters, value interface{}, levelQ, levelP, baseTwoDecomposition int) (pt *GadgetPlaintext, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}
