package rlwe

import (
	"io"

	"github.com/tuneinsight/lattigo/v6/ring"
	"github.com/tuneinsight/lattigo/v6/utils/sampling"
)

// Plaintext is a common base type for RLWE plaintexts.
type Plaintext struct {
	Element[ring.Poly]
	Value ring.Poly
}

// NewPlaintext creates a new [Plaintext] at the specified level from the parameters.
func NewPlaintext(params ParameterProvider, level ...int) (pt *Plaintext) {
	_ = "STUB: not implemented"
	return nil
}

// NewPlaintextAtLevelFromPoly constructs a new [Plaintext] at a specific level
// where the message is set to the passed poly. No checks are performed on poly and
// the returned [Plaintext] will share its backing array of coefficients.
// Returned plaintext's [MetaData] is allocated but empty.
func NewPlaintextAtLevelFromPoly(level int, poly ring.Poly) (pt *Plaintext, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Copy copies the supplied plaintext value into the receiver plaintext.
func (pt Plaintext) Copy(other *Plaintext) { _ = "STUB: not implemented"; return }

func (pt Plaintext) CopyNew() (ptCpy *Plaintext) { _ = "STUB: not implemented"; return nil }

// Equal performs a deep equal.
func (pt Plaintext) Equal(other *Plaintext) bool { _ = "STUB: not implemented"; return false }

// NewPlaintextRandom generates a new uniformly distributed [Plaintext].
func NewPlaintextRandom(prng sampling.PRNG, params ParameterProvider, level int) (pt *Plaintext) {
	_ = "STUB: not implemented"
	return nil
}

// ReadFrom reads on the object from an [io.Writer]. It implements the
// [io.ReaderFrom] interface.
//
// Unless r implements the [buffer.Reader] interface (see see lattigo/utils/buffer/reader.go),
// it will be wrapped into a [bufio.Reader]. Since this requires allocation, it
// is preferable to pass a buffer.Reader directly:
//
//   - When reading multiple values from a [io.Reader], it is preferable to first
//     first wrap io.Reader in a pre-allocated [bufio.Reader].
//   - When reading from a var b []byte, it is preferable to pass a buffer.NewBuffer(b)
//     as w (see lattigo/utils/buffer/buffer.go).
func (pt *Plaintext) ReadFrom(r io.Reader) (n int64, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// UnmarshalBinary decodes a slice of bytes generated by MarshalBinary
// or Read on the objeop.
func (pt *Plaintext) UnmarshalBinary(p []byte) (err error) { _ = "STUB: not implemented"; return nil }
