package rlwe

import (
	"math"
	"math/big"
)

const (
	// ScalePrecision is the default precision of the scale.
	ScalePrecision = uint(128)
)

var ScalePrecisionLog10 = int(math.Ceil(float64(ScalePrecision) / math.Log2(10)))

// Scale is a struct used to track the scaling factor
// of [Plaintext] and [Ciphertext] structs.
// The scale is managed as an 128-bit precision real and can
// be either a floating point value or a mod T
// prime integer, which is determined at instantiation.
type Scale struct {
	Value big.Float //`json:",omitempty"`
	Mod   *big.Int  //`json:",omitempty"`
}

// NewScale instantiates a new floating point [Scale].
// Accepted types for s are int, int64, uint64, float64, *[big.Int], *[big.Float] and *[Scale].
// If the input type is not an accepted type, returns an error.
func NewScale(s interface{}) Scale { _ = "STUB: not implemented"; return *new(Scale) }

// NewScaleModT instantiates a new integer mod T [Scale].
// Accepted types for s are int, int64, uint64, float64, *[big.Int], *[big.Float] and *[Scale].
// If the input type is not an accepted type, returns an error.
func NewScaleModT(s interface{}, mod uint64) Scale { _ = "STUB: not implemented"; return *new(Scale) }

// BigInt returns the scale as a big.Int, truncating the rational part and rounding ot the nearest integer.
// The rounding assumes that the scale is a positive value.
func (s Scale) BigInt() (sInt *big.Int) { _ = "STUB: not implemented"; return nil }

// Float64 returns the underlying scale as a float64 value.
func (s Scale) Float64() float64 { _ = "STUB: not implemented"; return 0 }

func (s Scale) Log2() float64 { _ = "STUB: not implemented"; return 0 }

// Uint64 returns the underlying scale as an uint64 value.
func (s Scale) Uint64() uint64 { _ = "STUB: not implemented"; return 0 }

// Mul multiplies the target s with s1, returning the result in
// a new [Scale] struct. If mod is specified, performs the multiplication
// modulo mod.
func (s Scale) Mul(s1 Scale) Scale { _ = "STUB: not implemented"; return *new(Scale) }

// Div multiplies the target s with s1^-1, returning the result in
// a new [Scale] struct. If mod is specified, performs the multiplication
// modulo t with the multiplicative inverse of s1. Otherwise, performs
// the quotient operation.
func (s Scale) Div(s1 Scale) Scale { _ = "STUB: not implemented"; return *new(Scale) }

// Cmp compares the target scale with s1.
// Returns 0 if the scales are equal, 1 if
// the target scale is greater and -1 if
// the target scale is smaller.
func (s Scale) Cmp(s1 Scale) (cmp int) { _ = "STUB: not implemented"; return 0 }

// Equal returns true if a == b.
func (s Scale) Equal(s1 Scale) bool { _ = "STUB: not implemented"; return false }

// InDelta returns true if abs(a-b) <= 2^{-log2Delta}
func (s Scale) InDelta(s1 Scale, log2Delta float64) bool { _ = "STUB: not implemented"; return false }

// Log2Delta returns -log2(abs(a-b)/max(a, b))
func (s Scale) Log2Delta(s1 Scale) float64 { _ = "STUB: not implemented"; return 0 }

// Max returns the a new scale which is the maximum
// between the target scale and s1.
func (s Scale) Max(s1 Scale) (max Scale) { _ = "STUB: not implemented"; return *new(Scale) }

// Min returns the a new scale which is the minimum
// between the target scale and s1.
func (s Scale) Min(s1 Scale) (max Scale) { _ = "STUB: not implemented"; return *new(Scale) }

// BinarySize returns the serialized size of the object in bytes.
// Each value is encoded with .Text('e', ceil(ScalePrecision / log2(10))).
func (s Scale) BinarySize() int {
	_ = "STUB: not implemented"
	// 21 for JSON formatting plus 2*(6 + ScalePrecisionLog10) for the scales encoding.
	return 0
}

// MarshalBinary encodes the object into a binary form on a newly allocated slice of bytes.
func (s Scale) MarshalBinary() (p []byte, err error) {
	_ = "STUB: not implemented"
	return nil,

		// UnmarshalBinary decodes a slice of bytes generated by
		// [Scale.MarshalBinary] on the object.
		nil
}

func (s Scale) UnmarshalBinary(p []byte) (err error) { _ = "STUB: not implemented"; return nil }

// MarshalJSON encodes the object into a binary form on a newly allocated slice of bytes.
func (s Scale) MarshalJSON() (p []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (s *Scale) UnmarshalJSON(p []byte) (err error) { _ = "STUB: not implemented"; return nil }

func scaleToBigFloat(scale interface{}) (s *big.Float) { _ = "STUB: not implemented"; return nil }

// Although the big.Float has 128 bits of precision, it will be
// initialized with mant:big.nat{0x0}, i.e. only one mantissa word.
// This forces two mantissa words: mant:big.nat{0x0, 0x0}.
