package ringqp

import (
	"io"

	"github.com/tuneinsight/lattigo/v6/ring"
)

// Poly represents a polynomial in the ring of polynomial modulo Q*P.
// This type is simply the union type between two ring.Poly, each one
// containing the modulus Q and P coefficients of that polynomial.
// The modulus Q represent the ciphertext modulus and the modulus P
// the special primes for the RNS decomposition during homomorphic
// operations involving keys.
type Poly struct {
	Q, P ring.Poly
}

// NewPoly creates a new polynomial at the given levels.
// If levelQ or levelP are negative, the corresponding polynomial will be nil.
func NewPoly(N, levelQ, levelP int) Poly { _ = "STUB: not implemented"; return *new(Poly) }

// LevelQ returns the level of the polynomial modulo Q.
// Returns -1 if the modulus Q is absent.
func (p Poly) LevelQ() int {
	_ = "STUB: not implemented"

	// LevelP returns the level of the polynomial modulo P.
	// Returns -1 if the modulus P is absent.
	return 0
}

func (p Poly) LevelP() int {
	_ = "STUB: not implemented"

	// Equal returns true if the receiver Poly is equal to the provided other Poly.
	return 0
}

func (p Poly) Equal(other *Poly) (v bool) { _ = "STUB: not implemented"; return false }

// Copy copies the coefficients of other on the target polynomial.
// This method simply calls the Copy method for each of its sub-polynomials.
func (p *Poly) Copy(other Poly) { _ = "STUB: not implemented"; return }

// CopyLvl copies the values of other on the target polynomial.
// The operation is performed at levelQ for the ringQ and levelP for the ringP.
func (p *Poly) CopyLvl(levelQ, levelP int, other Poly) { _ = "STUB: not implemented"; return }

// CopyNew creates an exact copy of the target polynomial.
func (p Poly) CopyNew() *Poly { _ = "STUB: not implemented"; return nil }

// Resize resizes the levels of the target polynomial to the provided levels.
// If the provided level is larger than the current level, then allocates zero
// coefficients, otherwise dereferences the coefficients above the provided level.
// Nil polynomials are unaffected.
func (p *Poly) Resize(levelQ, levelP int) { _ = "STUB: not implemented"; return }

// BinarySize returns the serialized size of the object in bytes.
// It assumes that each coefficient takes 8 bytes.
func (p Poly) BinarySize() (dataLen int) { _ = "STUB: not implemented"; return 0 }

// WriteTo writes the object on an io.Writer. It implements the io.WriterTo
// interface, and will write exactly object.BinarySize() bytes on w.
//
// Unless w implements the buffer.Writer interface (see lattigo/utils/buffer/writer.go),
// it will be wrapped into a bufio.Writer. Since this requires allocations, it
// is preferable to pass a buffer.Writer directly:
//
//   - When writing multiple times to a io.Writer, it is preferable to first wrap the
//     io.Writer in a pre-allocated bufio.Writer.
//   - When writing to a pre-allocated var b []byte, it is preferable to pass
//     buffer.NewBuffer(b) as w (see lattigo/utils/buffer/buffer.go).
func (p Poly) WriteTo(w io.Writer) (n int64, err error) { _ = "STUB: not implemented"; return 0, nil }

// ReadFrom reads on the object from an io.Writer. It implements the
// io.ReaderFrom interface.
//
// Unless r implements the buffer.Reader interface (see see lattigo/utils/buffer/reader.go),
// it will be wrapped into a bufio.Reader. Since this requires allocation, it
// is preferable to pass a buffer.Reader directly:
//
//   - When reading multiple values from a io.Reader, it is preferable to first
//     first wrap io.Reader in a pre-allocated bufio.Reader.
//   - When reading from a var b []byte, it is preferable to pass a buffer.NewBuffer(b)
//     as w (see lattigo/utils/buffer/buffer.go).
func (p *Poly) ReadFrom(r io.Reader) (n int64, err error) { _ = "STUB: not implemented"; return 0, nil }

// MarshalBinary encodes the object into a binary form on a newly allocated slice of bytes.
func (p Poly) MarshalBinary() (data []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalBinary decodes a slice of bytes generated by
// MarshalBinary or WriteTo on the object.
func (p *Poly) UnmarshalBinary(data []byte) (err error) { _ = "STUB: not implemented"; return nil }
