package buffer

import (
	"encoding"
	"io"
	"testing"
)

// binarySerializer is a testing interface for byte encoding and decoding.
type binarySerializer interface {
	BinarySize() int
	io.WriterTo
	io.ReaderFrom
	encoding.BinaryMarshaler
	encoding.BinaryUnmarshaler
}

// RequireSerializerCorrect tests that:
//   - input and output implement TestInterface
//   - input.WriteTo(io.Writer) writes a number of bytes on the writer equal to the number of bytes generated by input.MarshalBinary()
//   - input.WriteTo buffered bytes are equal to the bytes generated by input.MarshalBinary()
//   - output.ReadFrom(io.Reader) reads a number of bytes on the reader equal to the number of bytes written using input.WriteTo(io.Writer)
//   - applies require.Equalf between the original and reconstructed object for
//   - all the above WriteTo, ReadFrom, MarhsalBinary and UnmarshalBinary do not return an error
func RequireSerializerCorrect(t *testing.T, input binarySerializer) {
	_ = "STUB: not implemented"

	// Allocates a new object of the underlying type of input
	return
}

// Compliant to io.Writer and io.Reader

// Check io.Writer

// Checks that #bytes written = len(buffer)

// Check encoding.BinaryMarshaler

// Check that #bytes written with io.Writer = #bytes generates by encoding.BinaryMarshaler

// Check that bytes written with io.Writer = bytes generates by encoding.BinaryMarshaler

// Check io.Reader

// Check that #bytes read with io.Reader = #bytes written with io.Writer

// Deep equal output = input

// Check encoding.BinaryUnmarshaler

// Deep equal output = input

// EqualAsUint64 casts &T to an *uint64 and performs a comparison.
// User must ensure that T can be stored in an uint64.
func EqualAsUint64[T any](a, b T) bool {
	_ = "STUB: not implemented"
	/* #nosec G103 -- behavior and consequences well understood, pointer type cast */ return false
}

// EqualAsUint64Slice casts &[]T into *[]uint64 and performs a comparison.
// User must ensure that T can be stored in an uint64.
func EqualAsUint64Slice[T any](a, b []T) bool {
	_ = "STUB: not implemented"

	/* #nosec G103 -- behavior and consequences well understood, pointer type cast */
	return false
}

/* #nosec G103 -- behavior and consequences well understood, pointer type cast */

// EqualAsUint32Slice casts &[]T into *[]uint32 and performs a comparison.
// User must ensure that T can be stored in an uint32.
func EqualAsUint32Slice[T any](a, b []T) bool {
	_ = "STUB: not implemented"

	/* #nosec G103 -- behavior and consequences well understood, pointer type cast */
	return false
}

/* #nosec G103 -- behavior and consequences well understood, pointer type cast */

// EqualAsUint16Slice casts &[]T into *[]uint16 and performs a comparison.
// User must ensure that T can be stored in an uint16.
func EqualAsUint16Slice[T any](a, b []T) bool {
	_ = "STUB: not implemented"

	/* #nosec G103 -- behavior and consequences well understood, pointer type cast */
	return false
}

/* #nosec G103 -- behavior and consequences well understood, pointer type cast */

// EqualAsUint8Slice casts &[]T into *[]uint8 and performs a comparison.
// User must ensure that T can be stored in an uint8.
func EqualAsUint8Slice[T any](a, b []T) bool {
	_ = "STUB: not implemented"

	/* #nosec G103 -- behavior and consequences well understood, pointer type cast */
	return false
}

/* #nosec G103 -- behavior and consequences well understood, pointer type cast */
