package ring

import (
	"io"

	"github.com/tuneinsight/lattigo/v6/utils/structs"
)

// Poly is the structure that contains the coefficients of a polynomial.
type Poly struct {
	Coeffs structs.Matrix[uint64]
}

// NewPolyFromUintPool returns a new [Poly], built from backing []uint64 arrays obtained from a pool.
// After use, the [Poly] should be recycled using the [RecyclePolyInUintPool] method.
func NewPolyFromUintPool(pool structs.BufferPool[*[]uint64], level int) (pol *Poly) {
	_ = "STUB: not implemented"
	return nil
}

// RecyclePolyInUintPool takes a reference to a [Poly] and recycles its backing []uint64 arrays
// (i.e. they are returned to a pool). The input [Poly] must not be used after calling this method.
func RecyclePolyInUintPool(pool structs.BufferPool[*[]uint64], pol *Poly) {
	_ = "STUB: not implemented"
	return
}

// NewPoly creates a new polynomial with N coefficients set to zero and Level+1 moduli.
func NewPoly(N, Level int) (pol Poly) { _ = "STUB: not implemented"; return *new(Poly) }

// Resize resizes the level of the target polynomial to the provided level.
// If the provided level is larger than the current level, then allocates zero
// coefficients, otherwise dereferences the coefficients above the provided level.
func (pol *Poly) Resize(level int) { _ = "STUB: not implemented"; return }

// N returns the number of coefficients of the polynomial, which equals the degree of the Ring cyclotomic polynomial.
func (pol Poly) N() int { _ = "STUB: not implemented"; return 0 }

// Level returns the current number of moduli minus 1.
func (pol Poly) Level() int { _ = "STUB: not implemented"; return 0 }

// Zero sets all coefficients of the target polynomial to 0.
func (pol Poly) Zero() { _ = "STUB: not implemented"; return }

// CopyNew creates an exact copy of the target polynomial.
func (pol Poly) CopyNew() *Poly { _ = "STUB: not implemented"; return nil }

// Copy copies the coefficients of p1 on the target polynomial.
// This method does nothing if the underlying arrays are the same.
// This method will resize the target polynomial to the level of
// the input polynomial.
func (pol *Poly) Copy(p1 Poly) { _ = "STUB: not implemented"; return }

// CopyLvl copies the coefficients of p1 on the target polynomial.
// This method does nothing if the underlying arrays are the same.
// Expects the degree of both polynomials to be identical.
func (pol *Poly) CopyLvl(level int, p1 Poly) { _ = "STUB: not implemented"; return }

// Equal returns true if the receiver Poly is equal to the provided other Poly.
// This function checks for strict equality between the polynomial coefficients
// (i.e., it does not consider congruence as equality within the ring like
// `Ring.Equal` does).
func (pol Poly) Equal(other *Poly) bool { _ = "STUB: not implemented"; return false }

// BinarySize returns the serialized size of the object in bytes.
func (pol Poly) BinarySize() (size int) { _ = "STUB: not implemented"; return 0 }

// WriteTo writes the object on an io.Writer. It implements the io.WriterTo
// interface, and will write exactly object.BinarySize() bytes on w.
//
// Unless w implements the buffer.Writer interface (see lattigo/utils/buffer/writer.go),
// it will be wrapped into a bufio.Writer. Since this requires allocations, it
// is preferable to pass a buffer.Writer directly:
//
//   - When writing multiple times to a io.Writer, it is preferable to first wrap the
//     io.Writer in a pre-allocated bufio.Writer.
//   - When writing to a pre-allocated var b []byte, it is preferable to pass
//     buffer.NewBuffer(b) as w (see lattigo/utils/buffer/buffer.go).
func (pol Poly) WriteTo(w io.Writer) (n int64, err error) { _ = "STUB: not implemented"; return 0, nil }

// ReadFrom reads on the object from an io.Writer. It implements the
// io.ReaderFrom interface.
//
// Unless r implements the buffer.Reader interface (see see lattigo/utils/buffer/reader.go),
// it will be wrapped into a bufio.Reader. Since this requires allocation, it
// is preferable to pass a buffer.Reader directly:
//
//   - When reading multiple values from a io.Reader, it is preferable to first
//     first wrap io.Reader in a pre-allocated bufio.Reader.
//   - When reading from a var b []byte, it is preferable to pass a buffer.NewBuffer(b)
//     as w (see lattigo/utils/buffer/buffer.go).
func (pol *Poly) ReadFrom(r io.Reader) (n int64, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// MarshalBinary encodes the object into a binary form on a newly allocated slice of bytes.
func (pol Poly) MarshalBinary() (p []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalBinary decodes a slice of bytes generated by
// MarshalBinary or WriteTo on the object.
func (pol *Poly) UnmarshalBinary(p []byte) (err error) { _ = "STUB: not implemented"; return nil }
