package polynomial

import (
	"io"

	"github.com/tuneinsight/lattigo/v6/core/rlwe"
	"github.com/tuneinsight/lattigo/v6/schemes"
	"github.com/tuneinsight/lattigo/v6/utils/bignum"
	"github.com/tuneinsight/lattigo/v6/utils/structs"
)

// PowerBasis is a struct storing powers of a ciphertext.
type PowerBasis struct {
	bignum.Basis
	Value structs.Map[int, rlwe.Ciphertext]
}

// NewPowerBasis creates a new [PowerBasis]. It takes as input a ciphertext
// and a basis type. The struct treats the input ciphertext as a monomial X and
// can be used to generates power of this monomial X^{n} in the given [BasisType].
func NewPowerBasis(ct *rlwe.Ciphertext, basis bignum.Basis) (p PowerBasis) {
	_ = "STUB: not implemented"
	return *new(PowerBasis)
}

// SplitDegree returns a * b = n such that |a-b| is minimized
// with a and/or b odd if possible.
func SplitDegree(n int) (a, b int) { _ = "STUB: not implemented"; return 0, 0 }

//Necessary for optimal depth

// [Lee et al. 2020] : High-Precision and Low-Complexity Approximate Homomorphic Encryption by Error Variance Minimization
// Maximize the number of odd terms of Chebyshev basis
/* #nosec G115 -- previous check ensures n is greater than 0 */

// GenPower recursively computes X^{n}.
// If lazy = true, the final X^{n} will not be relinearized.
// Previous non-relinearized X^{n} that are required to compute the target X^{n} are automatically relinearized.
func (p *PowerBasis) GenPower(n int, lazy bool, eval schemes.Evaluator) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func (p *PowerBasis) genPower(n int, lazy, rescale bool, eval schemes.Evaluator) (rescaltOut bool, err error) {
	_ = "STUB: not implemented"
	return false, nil
}

// Recurses on the given indexes

// Avoids calling rescale on already generated powers

// Computes C[n] = C[a]*C[b]

// Cn = 2*Ca*Cb - Cc, n = a+b and c = abs(a-b)

// Computes C[n] = 2*C[a]*C[b]

// Computes C[n] = 2*C[a]*C[b] - C[c]

// Since C[0] is not stored (but rather seen as the constant 1), only recurses on c if c!= 0

// BinarySize returns the serialized size of the object in bytes.
func (p PowerBasis) BinarySize() (size int) { _ = "STUB: not implemented"; return 0 }

// WriteTo writes the object on an [io.Writer]. It implements the [io.WriterTo]
// interface, and will write exactly object.BinarySize() bytes on w.
//
// Unless w implements the [buffer.Writer] interface (see lattigo/utils/buffer/writer.go),
// it will be wrapped into a [bufio.Writer]. Since this requires allocations, it
// is preferable to pass a [buffer.Writer] directly:
//
//   - When writing multiple times to a [io.Writer], it is preferable to first wrap the
//     [io.Writer] in a pre-allocated [bufio.Writer].
//   - When writing to a pre-allocated var b []byte, it is preferable to pass
//     buffer.NewBuffer(b) as w (see lattigo/utils/buffer/buffer.go).
func (p PowerBasis) WriteTo(w io.Writer) (n int64, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

/* #nosec G115 -- Basis cannot be negative if receiver is valid */

// ReadFrom reads on the object from an [io.Writer]. It implements the
// [io.ReaderFrom] interface.
//
// Unless r implements the [buffer.Reader] interface (see see lattigo/utils/buffer/reader.go),
// it will be wrapped into a [bufio.Reader]. Since this requires allocation, it
// is preferable to pass a [buffer.Reader] directly:
//
//   - When reading multiple values from a [io.Reader], it is preferable to first
//     first wrap [io.Reader] in a pre-allocated [bufio.Reader].
//   - When reading from a var b []byte, it is preferable to pass a buffer.NewBuffer(b)
//     as w (see lattigo/utils/buffer/buffer.go).
func (p *PowerBasis) ReadFrom(r io.Reader) (n int64, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// MarshalBinary encodes the object into a binary form on a newly allocated slice of bytes.
func (p PowerBasis) MarshalBinary() (data []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary decodes a slice of bytes generated by
// [PowerBasis.MarshalBinary] or [PowerBasis.WriteTo] on the object.
func (p *PowerBasis) UnmarshalBinary(data []byte) (err error) {
	_ = "STUB: not implemented"
	return nil
}
